# Generated by Django 5.1.5 on 2026-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
